name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'adopt'  # You can use 'zulu' or 'temurin' as well

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B compile

      - name: Debug information
        run: |
          echo "Printing environment variables"
          env
          echo "Printing Java version"
          java -version
          echo "Printing Maven version"
          mvn -v
          echo "Printing current directory"
          pwd
          echo "Listing current directory contents"
          ls -la

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Make sure the token is stored as a secret in your repo
        with:
          args: >
            -Dsonar.projectKey=guilhermeVValerio_Spring-Boot-Example
            -Dsonar.organization=guilhermevvalerio
            -Dsonar.host.url=https://sonarcloud.io
